const recentPost = [
  {
    name: "Viethai Nguyen",
    profilePicture: "/images/profile.jpeg",
    postHour: "2h ago",
    position: "Yarn Supplier",
    email: "viethai@yopmail.com",
    fiber: "Polyester",
    image: "/images/imlage.png",
    negotiable: 1,
    origin: "Vietnam",
    price: "0.00",
    quality: "100% Polyester",
    quantity: 130,
    ref_no: "Y-177868184286539916",
    review: 0,
    shipment: "TBA",
    spec_details: "Kho e sẵn nhiều màu tơ, các bác lên đơn ạ",
    specialty_yarns: "Yes",
    yarn_count: "Ne 30/1",
  },
  {
    name: "Rahim Khan",
    profilePicture: "/images/profile.jpeg",
    postHour: "5h ago",
    position: "Textile Trader",
    email: "seller1@yopmail.com",
    fiber: "Cotton",
    image: "/images/imlage.png",
    negotiable: 0,
    origin: "Bangladesh",
    price: "2.50",
    quality: "100% Cotton",
    quantity: 200,
    ref_no: "Y-100000001",
    review: 4,
    shipment: "3-5 Days",
    spec_details: "High quality cotton yarn available",
    specialty_yarns: "Yes",
    yarn_count: "Ne 20/1",
  },
  {
    name: "Arjun Mehta",
    profilePicture: "/images/profile.jpeg",
    postHour: "1h ago",
    position: "Yarn Exporter",
    email: "supplier2@yopmail.com",
    fiber: "Viscose",
    image: "/images/imlage.png",
    negotiable: 1,
    origin: "India",
    price: "1.80",
    quality: "100% Viscose",
    quantity: 150,
    ref_no: "Y-100000002",
    review: 3,
    shipment: "7 Days",
    spec_details: "Soft viscose yarn for garments",
    specialty_yarns: "No",
    yarn_count: "Ne 30/2",
  },
  {
    name: "Olivia Smith",
    profilePicture: "/images/profile.jpeg",
    postHour: "3h ago",
    position: "Fabric Merchant",
    email: "seller3@yopmail.com",
    fiber: "Wool",
    image: "/images/imlage.png",
    negotiable: 0,
    origin: "Australia",
    price: "5.00",
    quality: "100% Wool",
    quantity: 80,
    ref_no: "Y-100000003",
    review: 5,
    shipment: "10 Days",
    spec_details: "Premium wool yarn for winter wear",
    specialty_yarns: "Yes",
    yarn_count: "Ne 16/1",
  },
  {
    name: "Chen Wei",
    profilePicture: "/images/profile.jpeg",
    postHour: "6h ago",
    position: "Industrial Supplier",
    email: "seller4@yopmail.com",
    fiber: "Nylon",
    image: "/images/imlage.png",
    negotiable: 1,
    origin: "China",
    price: "1.20",
    quality: "100% Nylon",
    quantity: 300,
    ref_no: "Y-100000004",
    review: 2,
    shipment: "5-7 Days",
    spec_details: "Strong nylon yarn for industrial use",
    specialty_yarns: "No",
    yarn_count: "Ne 40/1",
  },
  {
    name: "Ahmed Ali",
    profilePicture: "/images/profile.jpeg",
    postHour: "4h ago",
    position: "Textile Manufacturer",
    email: "seller5@yopmail.com",
    fiber: "Blended",
    image: "/images/imlage.png",
    negotiable: 1,
    origin: "Pakistan",
    price: "3.10",
    quality: "Cotton-Poly Blend",
    quantity: 220,
    ref_no: "Y-100000005",
    review: 4,
    shipment: "4 Days",
    spec_details: "Balanced blend yarn for apparel",
    specialty_yarns: "Yes",
    yarn_count: "Ne 24/1",
  },
  {
    name: "Elif Demir",
    profilePicture: "/images/profile.jpeg",
    postHour: "7h ago",
    position: "Export Agent",
    email: "seller6@yopmail.com",
    fiber: "Acrylic",
    image: "/images/imlage.png",
    negotiable: 0,
    origin: "Turkey",
    price: "2.00",
    quality: "100% Acrylic",
    quantity: 180,
    ref_no: "Y-100000006",
    review: 3,
    shipment: "6 Days",
    spec_details: "Soft acrylic yarn for sweaters",
    specialty_yarns: "No",
    yarn_count: "Ne 28/1",
  },
  {
    name: "Fatima Noor",
    profilePicture: "/images/profile.jpeg",
    postHour: "9h ago",
    position: "Linen Supplier",
    email: "seller7@yopmail.com",
    fiber: "Linen",
    image: "/images/imlage.png",
    negotiable: 1,
    origin: "Egypt",
    price: "4.20",
    quality: "100% Linen",
    quantity: 90,
    ref_no: "Y-100000007",
    review: 5,
    shipment: "8 Days",
    spec_details: "Premium linen yarn for luxury fabric",
    specialty_yarns: "Yes",
    yarn_count: "Ne 18/1",
  },
  {
    name: "Satoshi Tanaka",
    profilePicture: "/images/profile.jpeg",
    postHour: "10h ago",
    position: "Silk Trader",
    email: "seller8@yopmail.com",
    fiber: "Silk",
    image: "/images/imlage.png",
    negotiable: 0,
    origin: "Thailand",
    price: "8.00",
    quality: "100% Silk",
    quantity: 60,
    ref_no: "Y-100000008",
    review: 5,
    shipment: "12 Days",
    spec_details: "Luxury silk yarn for premium garments",
    specialty_yarns: "Yes",
    yarn_count: "Ne 60/1",
  },
  {
    name: "Lucas Martin",
    profilePicture: "/images/profile.jpeg",
    postHour: "8h ago",
    position: "Yarn Distributor",
    email: "seller9@yopmail.com",
    fiber: "Rayon",
    image: "/images/imlage.png",
    negotiable: 1,
    origin: "Indonesia",
    price: "2.80",
    quality: "100% Rayon",
    quantity: 140,
    ref_no: "Y-100000009",
    review: 4,
    shipment: "5 Days",
    spec_details: "Smooth rayon yarn for fashion wear",
    specialty_yarns: "No",
    yarn_count: "Ne 32/1",
  },
];

export default recentPost;
